image:
  tag: "d8260a80932b112ef8d59448f83f4cbcb4e97dd9"

containerPort: 3000   # port your app listens on inside the container

service:
  port: 3000          # ClusterIP port (same as containerPort for single-port HTTP apps)

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "3000"
  - name: ORIGIN
    value: https://cookiebookie.bybear.dk
