services:
  web:
    image:
      tag: "081919bc150dd630336542a570c5cf0311399139"
    ports:
      - name: http
        containerPort: 3000
        servicePort: 3000
        visibility: internet
    probes:
      port: http
      liveness:
        path: /
      readiness:
        path: /
    env:
      - name: NODE_ENV
        value: production
      - name: HOST
        value: "0.0.0.0"
      - name: PORT
        value: "3000"
      - name: ORIGIN
        value: https://cookiebookie.bybear.dk
